version: '3'
services: 
  db: 
    image: postgres:13.3
    volumes: 
      - ./tmp/db:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
  web: 
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes: 
      - .:/work
    ports: 
      - "3000:3000"
    depends_on: 
      - db

